SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS C
JOIN ITEM_TREE AS B
ON C.ITEM_ID = B.ITEM_ID
JOIN ITEM_INFO AS A
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE A.RARITY = "RARE"
ORDER BY C.ITEM_ID DESC

