SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d
WHERE EXISTS(SELECT 1
             FROM SKILLCODES s
             WHERE s.NAME IN ('Python', 'C#') AND
             d.SKILL_CODE & s.CODE > 0 )
ORDER BY ID