SELECT CONCAT('/home/grep/src/',A.BOARD_ID,'/',B.FILE_ID,B.FILE_NAME,B.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_FILE AS B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.BOARD_ID = (SELECT A.BOARD_ID FROM USED_GOODS_BOARD AS A ORDER BY A.VIEWS DESC LIMIT 1)
ORDER BY FILE_ID DESC
